version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/signal

hooks:

  AfterInstall:
    - location: aws_scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: aws_scripts/start_server.sh
      timeout: 60
      runas: ec2-user
  ApplicationStop:
    - location: aws_scripts/stop_server.sh
      runas: ec2-user