version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/signal
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  AfterInstall:
    - location: aws_scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: aws_scripts/start_server.sh
      timeout: 60
      runas: ec2-user
  ApplicationStop:
    - location: aws_scripts/stop_server.sh
      runas: ec2-user